웬만한 Css는 이제 거의 다 고친것같습니다
CleanBreath/cleanbreath-frontend pull request #40
Opened 2024-10-01 01:13 UTC by anyanswer1125

랜딩페이지 제작할때 쓸 화면 캡처하다가 깔끔하게 바꾸고싶어 눈에 보이는 거슬리는 부분들 수정했습니다!

2024-10-01 01:16 UTC, chansooda approved these changes
수고했어잉~

2024-10-04 11:03 UTC, choisiheon approved these changes
good

2024-10-05 07:02 UTC, CMU02 approved these changes
OK

2024-10-05 07:11 UTC, CMU02 requested changes
곧 있으면 메인 브랜치에 하루동안 보지 않기 기능이 추가가 되면 코드 최신화 해놓고 하면
다시 커밋 올려줘

2024-10-05 09:54 UTC, CMU02 approved these changes
OK

2024-10-05 09:55 UTC, merged