흡연구역 추가하기(branc 새로만들어서 수정 )
CleanBreath/cleanbreath-frontend pull request #8
Opened 2024-08-01 01:37 UTC by chansooda

리뷰부탁드려요 시간날때(addArea module css추가)

2024-08-05 01:11 UTC, CMU02 approved these changes
LGTM

2024-08-05 02:09 UTC, choisiheon approved these changes
good

2024-08-05 11:55 UTC, kgw-coding requested changes
오타 수정
폐쇠형 -> 폐쇄형
으로 부탁드립니다

2024-08-05 11:56 UTC, CMU02 commented on src/components/addComponent.tsx
> +                        폐쇠형
폐쇠 -> 폐쇄형으로 바꿔주세요.

2024-08-08 00:53 UTC, kgw-coding approved these changes
오타수정 확인 good

2024-08-09 05:09 UTC, chansooda commented on package.json
json 건드는게 아닌듯 삭제 해보니깐 allRequestData 로들어가니 제출 데이터값이 안나와서 다시 집어넣으니까 나왔어요 그냥 신경x

2024-08-12 02:39 UTC, rnujhgd approved these changes
확인

2024-08-15 06:56 UTC, closed without merging